name: Tests on OS X

on: [push]

jobs:
  build-osx:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
    - name: Build conda package
      run: |
        conda install --yes --quiet conda-build
        conda build -c spyking-circus -c conda-forge conda_recipe
      shell: bash -l {0}
    - name: Publish Conda package
      if: startsWith(github.ref, 'refs/tags')
      run: |
        conda install --yes --quiet anaconda-client
        anaconda -t "$ANACONDA_TOKEN" upload \
        /usr/local/miniconda/envs/test/conda-bld/osx-64/spyking-circus*.tar.bz2 \
        -u spyking-circus
      shell: bash -l {0}
      env:
        ANACONDA_TOKEN: ${{ secrets.anaconda_token }}
